### PR TITLE
compliance tests: password auth & sudoers' user_list

### LINKED ISSUE #99: sudoers: `%root` and `%#0` fail with 'Error: Authentication("no permission")'
failing tests:

https://github.com/memorysafety/sudo-rs/blob/e5233df26ea0d5f46f71707bb78c54631065305d/test-framework/sudo-compliance-tests/src/sudoers/user_list.rs#L66

https://github.com/memorysafety/sudo-rs/blob/e5233df26ea0d5f46f71707bb78c54631065305d/test-framework/sudo-compliance-tests/src/sudoers/user_list.rs#L79

the original sudo passes both tests

### PR DESCRIPTION
**Pull request by japaric**
I ended doing a U turn towards the end of the commit history but I think focusing on the orthogonality of the tests is a change for the better.

this is best reviewed commit by commit

cc #96
closes #99

### CODE REVIEW

File: test-framework/sudo-test/src/lib.rs [hunk 1]
```diff
@@ -150,9 +193,45 @@ impl EnvBuilder {
 
         let container = Container::new(BASE_IMAGE)?;
 
-        let mut groups = get_groups(&container)?;
         let mut users = get_users(&container)?;
 
+        for username in &users {
```
Comment (japaric) [inline test-framework/sudo-test/src/lib.rs:198]: this function has gotten quite gnarly. I'll look next into refactoring the sudo-test crate: introducing an intermediate representation should simplify this `build` function. I also want to tweak the API to be more "builder like" and avoid so many `None` and `&[]` arguments in method calls (in the compliance tests).

File: test-framework/sudo-test/src/lib.rs [hunk 2]
```diff
@@ -477,4 +622,79 @@ mod tests {
...
+    #[should_panic = "cannot override the group ID of system group root"]
+    fn override_root_group_id_fails() {
+        EnvBuilder::default()
+            .group_id("root", 1000)
+            .build()
+            .unwrap();
+    }
+
+    #[test]
+    #[should_panic = "cannot assign user ID to non-existent user ferris"]
```
Comment (pvdrz) [inline test-framework/sudo-test/src/lib.rs:642]: sad crab noises :crab:

File: test-framework/sudo-compliance-tests/src/pass_auth.rs [hunk 3]
```diff
@@ -140,3 +140,51 @@ fn user_cannot_sudo_if_user_is_in_sudoers_file_and_password_is_not_provided() ->
 
     Ok(())
 }
+
+#[ignore]
+#[test]
+fn user_can_sudo_if_user_id_is_in_sudoers_file_and_correct_password_is_provided() -> Result<()> {
```
Comment (pvdrz) [inline test-framework/sudo-compliance-tests/src/pass_auth.rs]: These names are getting out of control :rofl:

**Review by pvdrz — APPROVED** [review]
