### PR TITLE
Added resolve_path to EDITOR and fix resolve_path test

### LINKED ISSUE #724: visudo does not resolve editor path
Currently visudo does not resolve a path through the PATH variable.

# Example
- ```export EDITOR=nvim```
- cargo run --bin visudo

visudo will not find nvim because it does not look for nvim in the PATH.
The correct usage would be this:
- ```export EDITOR=/usr/bin/nvim```
- cargo run --bin visudo

### PR DESCRIPTION
**Pull request by oneElectron**
This resolves #724.
Previous pull request was: #727.

### CODE REVIEW

File: src/sudoers/mod.rs [hunk 1]
```diff
@@ -158,6 +159,13 @@ impl Sudoers {
                     if can_execute(path) {
                         return Some(path.to_owned());
                     }
+                    let path = resolve_path(
+                        path,
+                        &std::env::var("PATH").unwrap_or(env!("DEFAULT_PATH").to_string()),
+                    );
+                    if let Some(path) = path {
```
Comment (squell) [inline src/sudoers/mod.rs:166]: One question: shouldn't we again check for `can_execute` after the path resolution and return `None` otherwise? (That might involve a small refactor on this code so we don't repeat ourselves)

Comment (oneElectron) [reply src/sudoers/mod.rs:166]: I don't know if that is really necessary because the resolve_path function also tests to see if the file it found is executable.

Comment (squell) [reply src/sudoers/mod.rs:166]: Right, thanks! In that case we can merge this as-is. Thanks for the contribution!
