### PR TITLE
su cli and group handling fixes

### LINKED ISSUE #532: `su -l` should preserve env var `TERM`
relevant test

https://github.com/memorysafety/sudo-rs/blob/af4971ee381874f283d09f5c8ba80c895bb59c90/test-framework/sudo-compliance-tests/src/su/flag_login.rs#L130-L141

### LINKED ISSUE #533: `su -p` should preserve HOME, SHELL, USER and LOGNAME
relevant tests:

https://github.com/memorysafety/sudo-rs/blob/f258f2b84eebef55a072468b3f4e111d0258e813/test-framework/sudo-compliance-tests/src/su/flag_preserve_environment.rs#L6-L21

https://github.com/memorysafety/sudo-rs/blob/f258f2b84eebef55a072468b3f4e111d0258e813/test-framework/sudo-compliance-tests/src/su/flag_preserve_environment.rs#L27-L48

### LINKED ISSUE #552: `su -g` / `su -G` should not work when the invoking user is not root
relevant tests

https://github.com/memorysafety/sudo-rs/blob/74f3992320b964ebf16dd6dfcc057e2cf47cca46/test-framework/sudo-compliance-tests/src/su/flag_group.rs#L23-L47

https://github.com/memorysafety/sudo-rs/blob/2ea5d86ccfc0c0d62084a261e369fc6f1eca7e56/test-framework/sudo-compliance-tests/src/su/flag_supp_group.rs#L105-L129

ogsu:

``` console
$ whoami
ferris

$ su -g users
su: only root can specify alternative groups
```

### LINKED ISSUE #553: `su -g some-group` should _override_ the invoking user primary group
relevant test

https://github.com/memorysafety/sudo-rs/blob/2ea5d86ccfc0c0d62084a261e369fc6f1eca7e56/test-framework/sudo-compliance-tests/src/su/flag_group.rs#L23-L33

ogsu
``` console
# su -g users -c id
uid=0(root) gid=100(users) groups=100(users)
```

su-rs (note the extra `root` in the group list)
``` console
# su -g users -c id
uid=0(root) gid=100(users) groups=100(users),0(root)
```

### LINKED ISSUE #554: su/cli: not passing an argument to flags that expect one results in a panic
``` console
# su -G
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "no supplementary group provided"', src/su/mod.rs:96:44

# su -g
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "no group provided"', src/su/mod.rs:96:44

# su -c
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "no command provided"', src/su/mod.rs:96:44
```

### LINKED ISSUE #555: `su -G some-group` should not preserve the invoking user's groups
relevant test

https://github.com/memorysafety/sudo-rs/blob/2ea5d86ccfc0c0d62084a261e369fc6f1eca7e56/test-framework/sudo-compliance-tests/src/su/flag_supp_group.rs#L6-L17

ogsu
``` console
# su -G users -c 'id -G'
100
```

su-rs
``` console
# su -G users -c 'id -G'
100 0
```

### LINKED ISSUE #556: `su -G a -G b` appears to ignore the first `-G` argument
relevant tests

https://github.com/memorysafety/sudo-rs/blob/2ea5d86ccfc0c0d62084a261e369fc6f1eca7e56/test-framework/sudo-compliance-tests/src/su/flag_supp_group.rs#L40-L55

https://github.com/memorysafety/sudo-rs/blob/2ea5d86ccfc0c0d62084a261e369fc6f1eca7e56/test-framework/sudo-compliance-tests/src/su/flag_supp_group.rs#L61-L77

all `-G` arguments should be used as target groups and the first `-G` argument should become the primary group

ogsu
``` console
# groupadd a -g 1000
# groupadd b -g 1001

# su -G a -G b -c 'id -G'
1000 1001
```

su-rs
``` console
# groupadd a -g 1000
# groupadd b -g 1001

# su -G a -G b -c 'id -G'
1001 0
```

### LINKED ISSUE #569: `su --help` should list available options / flags
su-rs
``` console
# su --help
Usage: su [options] [-] [<user> [<argument>...]]
```

ogsu
``` console
# su --help

Usage:
 su [options] [-] [<user> [<argument>...]]

Change the effective user ID and group ID to that of <user>.
A mere - implies -l.  If <user> is not given, root is assumed.

Options:
 -m, -p, --preserve-environment      do not reset environment variables
 -w, --whitelist-environment <list>  don't reset specified variables
(..)
```

### LINKED ISSUE #581: `su -g a -g b` should add both `a` and `b` to the group list of the target user
relevant test

https://github.com/memorysafety/sudo-rs/blob/86218b194b5c06fba79e6232c24a53daf9a761ed/test-framework/sudo-compliance-tests/src/su/flag_group.rs#L71-L86

likely related to #556

### LINKED ISSUE #582: `su -l some-user` should print a warning when the home directory of the target user does not exist
relevant test

https://github.com/memorysafety/sudo-rs/blob/86218b194b5c06fba79e6232c24a53daf9a761ed/test-framework/sudo-compliance-tests/src/su/flag_login.rs#L179-L194

### LINKED ISSUE #583: su: `-s` and `SHELL` should be ignored when the target user has a restricted shell in `/etc/passwd`
relevant tests

https://github.com/memorysafety/sudo-rs/blob/86218b194b5c06fba79e6232c24a53daf9a761ed/test-framework/sudo-compliance-tests/src/su/flag_shell.rs#L98

https://github.com/memorysafety/sudo-rs/blob/86218b194b5c06fba79e6232c24a53daf9a761ed/test-framework/sudo-compliance-tests/src/su/flag_preserve_environment.rs#L96

ogsudo (pass auth omitted for brevity)
``` console
$ whoami
ferris

$ grep ghost /etc/passwd
ghost:x:1001:1003::/home/ghost:/tmp/restricted-shell.sh

$ cat /tmp/restricted-shell.sh
#!/bin/sh
echo this is a restricted shell

$ su ghost
this is a restricted shell

$ su -s /usr/bin/env ghost
su: using restricted shell /tmp/restricted-shell.sh
this is a restricted shell

$ env SHELL=/usr/bin/env su -p ghost
su: using restricted shell /tmp/restricted-shell.sh
this is a restricted shell
```

sudo-rs
``` console
$ env -i su -s /usr/bin/env ghost
HOME=/home/ghost
LOGNAME=ghost
MAIL=/var/mail/ghost
SHELL=/usr/bin/env
USER=ghost
__LLVM_PROFILE_RT_INIT_ONCE=__LLVM_PROFILE_RT_INIT_ONCE

$ env -i SHELL=/usr/bin/env su -p ghost
MAIL=/var/mail/ghost
SHELL=/usr/bin/env
__LLVM_PROFILE_RT_INIT_ONCE=__LLVM_PROFILE_RT_INIT_ONCE
```

note that `root` is not subject to this restriction and can use both `-s` and `SHELL` to change the shell

### LINKED ISSUE #584: `su -w a -w b` should preserve env vars `a` and `b`
relevant test

https://github.com/memorysafety/sudo-rs/blob/86218b194b5c06fba79e6232c24a53daf9a761ed/test-framework/sudo-compliance-tests/src/su/flag_whitelist_environment.rs#L119

ogsudo
``` console
# env FOO=42 BAR=24 BAZ=33 su -w FOO,BAR -w BAZ -l -s /usr/bin/env
SHELL=/usr/bin/env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOME=/root
USER=root
LOGNAME=root
FOO=42
BAR=24
BAZ=33
TERM=xterm
MAIL=/var/mail/root
```

sudo-rs
``` console
# env FOO=42 BAR=24 BAZ=33 su -w FOO,BAR -w BAZ -l -s /usr/bin/env
BAZ=33
HOME=/root
LOGNAME=root
MAIL=/var/mail/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SHELL=/usr/bin/env
USER=root
```

### PR DESCRIPTION
**Pull request by marlonbaeten**
Fixes #532
Fixes #533 
Fixes #552
Fixes #552
Fixes #553
Fixes #554
Fixes #555
Fixes #556
Fixes #569 
Fixes #581
Fixes #582
Fixes #583
Fixes #584

### CODE REVIEW

File: src/su/context.rs [hunk 1]
```diff
@@ -23,6 +27,19 @@ pub(crate) struct SuContext {
     pub(crate) process: Process,
 }
 
+/// check that a shell is not restricted / exists in /etc/shells
+fn is_restricted(shell: &Path) -> bool {
+    if let Some(pattern) = shell.as_os_str().to_str() {
+        if let Ok(contents) = fs::read_to_string(VALID_LOGIN_SHELLS_LIST) {
+            if contents.contains(pattern) {
```
Comment (japaric) [inline src/su/context.rs:34]: `/etc/shells` can contain comments. this will consider commented out shells as non-restricted shells

Comment (marlonbaeten) [reply src/su/context.rs:34]: Nice catch - I'll check whether the shell corresponds to a full line in this file

Comment (marlonbaeten) [reply src/su/context.rs]: Fixed in [ba72489](https://github.com/memorysafety/sudo-rs/pull/590/commits/ba72489170125c479fd97e3d00c04dd898ea5e73)
