### PR TITLE
Pam fixes

### LINKED ISSUE #269: PAM_DATA_SILENT is not set in pam_end
You apply `| PAM_DATA_SILENT` to the return value not to the flags.

https://github.com/memorysafety/sudo-rs/blob/fe8bf15a238cc48c4518fe9d5ec593fdef89d863/lib/sudo-pam/src/lib.rs#L488

In the [original PR](https://github.com/systemd/systemd/pull/22341/files#diff-02a5af3cd0cd939690b4d5510491080783d2cf584b28f4422b962863c404f521R1342) this is how they set it:

```
(void) pam_end(handle, pam_code | flags | PAM_DATA_SILENT);
```

### PR DESCRIPTION
**Pull request by rnijveld**
Fixes #269, #270, #271 and #273

### CODE REVIEW

**Review by pvdrz — APPROVED** [review]

File: lib/sudo-pam/src/lib.rs [hunk 1]
```diff
@@ -472,21 +459,17 @@ impl<'a, C: Converser> Drop for PamContext<'a, C> {
...
+        let _ = self.close_session();
+
+        // It looks like PAM_DATA_SILENT is important to set for our sudo context, but
+        // it is unclear what it really does and does not do, other than the vague
+        // documentation description to 'not take the call to seriously'
+        // Also see https://github.com/systemd/systemd/issues/22318
+        unsafe {
+            pam_end(
+                self.pamh,
+                self.last_pam_status.unwrap_or(PAM_SUCCESS as libc::c_int) | PAM_DATA_SILENT as i32,
```
Comment (kpp) [inline lib/sudo-pam/src/lib.rs:471]: I would make a temp var for flags to make the code clearer but anyway thanks for fixing it.

File: lib/sudo-pam/src/lib.rs [hunk 2]
```diff
@@ -99,8 +90,14 @@ impl<C: Converser> PamContextBuilder<C> {
             if pamh.is_null() {
                 Err(PamError::InvalidState)
             } else {
-                context.pamh = Some(unsafe { &mut *pamh });
-                Ok(context)
+                Ok(PamContext {
+                    data_ptr,
+                    pamh: unsafe { &mut *pamh },
```
Comment (kpp) [inline lib/sudo-pam/src/lib.rs:95]: Would you please explain why this is safe?

Comment (rnijveld) [reply lib/sudo-pam/src/lib.rs:95]: Firstly, we've passed a pointer to null that was changed by `pam_start` to something else because we check that it is no longer null. Secondly we check there were no errors given by `pam_start`. Those two facts combined should be enough to confirm that a valid pamh pointer is now in `pamh` and can thus safely be converted to a reference. We then convert to a reference only to make sure that there won't be any ownership or lifetime issues going forward (i.e. we can't just leak the ptr and get into all the nasty memory safety issues). The FFI functions that we call do indeed take a ptr, but passing a ref makes no runtime difference, and we might as well have a safe reference instead of a possibly unsafe ptr.
